# kubernetes/backstage.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labelsBackstage }}
  template:
    metadata:
      labels:
        app: {{ .Values.labelsBackstage }}
    spec:
      containers:
        - name: backstage
          image: "{{ .Values.imageBackstage.repository }}:{{ .Values.imageBackstage.tag }}"
          imagePullPolicy: {{ .Values.imageBackstage.pullPolicy }}
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: backstage-secrets