apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_TOKEN: VG9rZW5Ub2tlblRva2VuVG9rZW5NYWxrb3ZpY2hUb2tlbg==
  BACKSTAGE_DB_HOST: ZGV2b3BzLXNvbmFycXViZS1yYS1wb3N0Z3Jlcy1ucC5jYzd1c3ZzZmp4dmoudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  BACKSTAGE_DB_PORT: NTQzMg==
  POSTGRES_USER: 
  POSTGRES_PASSWORD: 