# kubernetes/backstage-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.labelsBackstage }}
  ports:
    - name: http
      port: 80
      targetPort: http