apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: andrewf-cronjob-aws-ls
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kuber
    server: https://kubernetes.default.svc
  project: devel
  source:
    path: cronjob-andrewf
    repoURL: git@github.com:afaleichyk/test-argo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
