apiVersion: batch/v1
kind: CronJob
metadata:
  name: andrewf-cronjob-aws-ls-1
  namespace: kuber
spec:
  concurrencyPolicy: Forbid
  schedule: "35 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: aws-cli-container
              image: woahbase/alpine-awscli
              command:
                - sh
                - -c
                - echo "Hello from Andrew"

